### ISSUE TITLE
Errors with the atmosphere rendering with missing background image

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1093]
If the MilkywaySphere is disabled, the atmosphere shows errors in rendering.  I'd assume some wrong depth values being set for the clear in the beginning of the frame?

Repro:
1. Move camera into Earth atmosphere and tilt upwards
1. Disable the MilkywaySphere rendering

![Image from iOS (4)](https://user-images.githubusercontent.com/4921724/74859600-9bce6680-5347-11ea-90a4-0d6f5948efce.jpg)
![Image from iOS (3)](https://user-images.githubusercontent.com/4921724/74859615-a0931a80-5347-11ea-8cf7-1707e3c99a07.jpg)
![Image from iOS (1)](https://user-images.githubusercontent.com/4921724/74859618-a12bb100-5347-11ea-93e3-c46627c02476.jpg)

**Comment by jccosta** [comment]
That behavior is not a bug; it is by design. The problem here is with the depth information in the G-Buffer. When the background sphere is not drawn, the G-Buffer has 0.0 as the depth information stored. Then the atm acts as something is in front of the ray being traced.
To solve this problem, we need to initialize the G-Buffer with a value different than 0.0, which would add an extra call for a clear procedure, decreasing the performance.
If we have a specific case where the atm must be drawn w/o a background galaxy image, we will need to add that extra clear procedure.
Let me know what you think, @alexanderbock

**Comment by jccosta** [comment]
Fixed in 2272eac822f389e0f0166332b7f0102f8f74a094

**Comment by alexanderbock** [comment]
The second problem is still there:

http://weber.itn.liu.se/~alebo68/tmp/atm-milkyway.mp4

**Comment by jccosta** [comment]
Other renderable was affecting the initial solution. I fixed it. @alexanderbock can you give it a try now?

**Comment by alexanderbock** [comment]
👍   It works and is merged
