### ISSUE TITLE
Return of the Stair Stepping (of heightmap)

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2472]
Stair stepping of the height map has been reintroduced. Seen easiest when accurate normals is enabled. This is happening even when turning off the stereoscopic depth.

See attached screenshots of random place on the moon in v17.2 vs v18/master.

![OpenSpace_000000](https://user-images.githubusercontent.com/708535/216125990-6cef1084-4593-4be7-9cff-ecc3bb23813d.png)
![OpenSpace_000001](https://user-images.githubusercontent.com/708535/216125996-435209fd-f776-4562-914e-13f14bafe88d.png)
![OpenSpace_000000](https://user-images.githubusercontent.com/708535/216126010-105b7719-fb60-4f3a-9bc8-889b5c01950b.png)
![OpenSpace_000001](https://user-images.githubusercontent.com/708535/216126014-1eb80791-3f81-438c-beec-8db0142a1d84.png)

**Comment by alexanderbock** [comment]
Fixed;  we subsampled the height map to a glorious resolution of 64x64

![OpenSpace_000000](https://user-images.githubusercontent.com/4921724/229607388-5569a18a-9b59-4e7e-b08d-5ec5f837f788.png)

**Comment by micahnyc** [comment]
Still happening for LROC dems.  probably all  globebrowsing files added with tif/vrt

![image](https://user-images.githubusercontent.com/708535/235179320-ae283b1c-6522-45e5-a691-2b2218a8412a.png)

**Comment by alexanderbock** [comment]
Which files are they?

**Comment by micahnyc** [comment]
These are the ones from our website download for the apollo sites.

**Comment by alexanderbock** [comment]
9447a351b4a3d41a432dd7dbe0edd04fa370a667 should address some of that.  I still see some stairstepping, but I believe that it is included in the data.

We might want to consider removing the info parts and loading the files from OnMoon instead?

**Comment by alexanderbock** [comment]
@micahnyc  Need feedback on if it is fixed

**Comment by micahnyc** [comment]
seems to still be happening on mars in WCC

![image](https://github.com/OpenSpace/OpenSpace/assets/708535/cf3375d0-37d0-4bfd-96de-b7581214442a)

**Comment by alexanderbock** [comment]
Stair stepping does not seem to occur in the image data

![OpenSpace_000001](https://github.com/OpenSpace/OpenSpace/assets/4921724/971ba741-bbcc-4e64-ae43-fe76c29b5ea1)
![OpenSpace_000002](https://github.com/OpenSpace/OpenSpace/assets/4921724/1fc45042-f5c6-457b-8591-3e93d69efea1)

**Comment by alexanderbock** [comment]
Steps to reproduce:

```lua
openspace.setPropertyValueSingle("Scene.Mars.Renderable.Layers.ColorLayers.MOC_WA_Color_LiU.Enabled", true)
openspace.setPropertyValueSingle("Scene.Mars.Renderable.Layers.ColorLayers.MOC_WA_Color_Utah.Enabled", false)
openspace.setPropertyValueSingle("Scene.Mars.Renderable.Layers.Overlays.Indices.Enabled", true)
openspace.setPropertyValueSingle("Scene.Mars.Renderable.Layers.ColorLayers.BlendTileLevels", false)
openspace.setPropertyValueSingle("Scene.Mars.Renderable.Layers.HeightLayers.BlendTileLevels", false)
openspace.setPropertyValueSingle("Scene.Mars.Renderable.Layers.Overlays.BlendTileLevels", false)
openspace.setPropertyValueSingle("Scene.Mars.Renderable.UseAccurateNormals", true)
openspace.setPropertyValueSingle("Scene.Mars.Renderable.Debug.ShowChunkEdges", true)
openspace.setPropertyValue("Scene.*.Renderable.Enabled", false)
openspace.setPropertyValueSingle("Scene.Mars.Renderable.Enabled", true)
openspace.navigation.loadNavigationState(openspace.absPath("${BASE}/stair-stepping.txt"))
```

with stair-stepping.txt:
```lua
return {Anchor="Mars",Pitch=1.3783712052055024,Position={833376.3612414809,-3270631.263819751,-412781.6585985826},Up={-0.9018446993637969,-0.27214803646496544,0.33557649571697823},Yaw=-0.05179361503699984}
```

**Comment by alexanderbock** [comment]
Might be related to an offset in the texel values. Each tile has a uniform color in the image, note that the height information doesn't start on a tile boundary:

![OpenSpace_000000](https://github.com/OpenSpace/OpenSpace/assets/4921724/bf6d1a8f-f711-4c6b-a8b2-7536add21b1f)
