### ISSUE TITLE
Night Sky actionissue in dome

### ISSUE THREAD

**Issue by Arohdin** [OpenSpace/OpenSpace#2854]
The action to show Cardinal directions is local and only shows on master and not on the dome.

**Comment by WeirdRubberDuck** [comment]
Probably related to #2768

**Comment by Roxeena** [comment]
Writing this here to have it documented. The cause for this issue is that the nodes in the cluster get errors when trying to run some of the night sky scripts. The error is that the script requires the anchor node to be a `RenderableGlobe` and that the current anchor is not. Some more digging revealed that it is true; when OpenSpace is started up in a multi-node setup,  the nodes do not have Earth as the anchor node. See the logs further down.

A fix that users can use temporarily is to start by refocusing on the current anchor node when using a multi-node setup. This will make sure that the proper anchor node is set for all nodes in the cluster. 

Master log:
```lua
Position = {
    [1] = 3193540.8439321117,
    [2] = 927350.0388213138,
    [3] = 5445348.30897506
},
Up = {
    [1] = -0.8073394164383654,
    [2] = -0.2775363194473196,
    [3] = 0.5207462511171785
},
Yaw = -0.03474469877913512,
Anchor = "Earth",
Pitch = 1.643831997457059
```

Node log:
```lua
Position = {
    [1] = 59198915290.64543,
    [2] = 73862128453.09225,
    [3] = -116540410893.4791
},
Pitch = -1.7829577178929965,
Yaw = 1.319395256985424,
Anchor = "Root",
Up = {
    [1] = 0.8554643649066723,
    [2] = -0.5050564071385557,
    [3] = 0.11444975309330188
}
```

The error in the node log:
```
Error executing script '': [string " openspace.setPropertyValueSingle("Scene.C..."]:1: Focus node must be a RenderableGlobe
```
Raw logs:
[debugging-anchor.zip](https://github.com/OpenSpace/OpenSpace/files/12474970/debugging-anchor.zip)

**Comment by WeirdRubberDuck** [comment]
It is probably worth checking if the same problem occurs if the camera is set from a navigation state in the profile, or just a node. Because I assume this check was done in the default profile? (that one sets it based on a lat long geo position)

When the camera is set from a lat long position, we actually run a script that sets the camera position. I.e. in this case it is actually set using Lua code.

In the other two situations, setting from navigation state or just a scene graph node, we use internal C++ code (in the NavigationHandler) to set the camera state next frame

**Comment by alexanderbock** [comment]
Fixed in a7dca9a4fc2e35907eaeca338b9ab1e471dfe616

**Comment by Roxeena** [comment]
PR #2872 does not solve this issue, syncing out the anchor node will but that will be a separate PR.
