### ISSUE TITLE
Build fails in Linux after a recent commit

### ISSUE THREAD

**Issue by wtbgagoa** [OpenSpace/OpenSpace#3615]
I am maintaining the [ArchLinux package](https://aur.archlinux.org/packages/openspace-git) of OpenSpace and the recent commit [b5541](https://github.com/OpenSpace/OpenSpace/commit/b554187d76e51934f49c3d337de7302ff30228f3) introduces the following error when building:
```
[ 85%] Building CXX object src/CMakeFiles/openspace-core.dir/scene/rotation.cpp.o
[ 85%] Building CXX object src/CMakeFiles/openspace-core.dir/scene/scale.cpp.o
[ 85%] Building CXX object src/CMakeFiles/openspace-core.dir/scene/scene.cpp.o
[ 85%] Building CXX object src/CMakeFiles/openspace-core.dir/scene/sceneinitializer.cpp.o
[ 85%] Building CXX object src/CMakeFiles/openspace-core.dir/scene/scenegraphnode.cpp.o
[ 85%] Building CXX object src/CMakeFiles/openspace-core.dir/scene/timeframe.cpp.o
In file included from /home/alfonso/openspace-git/src/OpenSpace/ext/ghoul/include/ghoul/lua/lua_helper.inl:30,
                 from /home/alfonso/openspace-git/src/OpenSpace/ext/ghoul/include/ghoul/lua/lua_helper.h:620,
                 from /home/alfonso/openspace-git/src/OpenSpace/build/src/CMakeFiles/openspace-core.dir/cmake_pch.hxx:9,
                 from <command-line>:
/usr/include/oneapi/tbb/task_group.h:588:21: error: non-local lambda expression cannot have a capture-default
  588 |     d2::task_handle defer(F&& f) {
      |                     ^~~~~
In file included from /usr/include/oneapi/tbb/partitioner.h:47,
                 from /usr/include/oneapi/tbb/parallel_for.h:27,
                 from /usr/include/tbb/parallel_for.h:17,
                 from /usr/include/c++/14.2.1/pstl/parallel_backend_tbb.h:25,
                 from /usr/include/c++/14.2.1/pstl/parallel_backend.h:20,
                 from /usr/include/c++/14.2.1/pstl/algorithm_impl.h:22,
                 from /usr/include/c++/14.2.1/pstl/glue_execution_defs.h:50,
                 from /usr/include/c++/14.2.1/execution:39,
                 from /home/alfonso/openspace-git/src/OpenSpace/src/scene/scene_lua.inl:61,
                 from /home/alfonso/openspace-git/src/OpenSpace/src/scene/scene.cpp:39:
/usr/include/oneapi/tbb/task_group.h: In lambda function:
/usr/include/oneapi/tbb/task_group.h:588:26: error: expected ‘{’ before ‘(’ token
  588 |     d2::task_handle defer(F&& f) {
      |                          ^
/usr/include/oneapi/tbb/task_group.h: At global scope:
/usr/include/oneapi/tbb/task_group.h:588:28: error: expected primary-expression before ‘&&’ token
  588 |     d2::task_handle defer(F&& f) {
      |                            ^~
/usr/include/oneapi/tbb/task_group.h:588:31: error: ‘f’ was not declared in this scope
  588 |     d2::task_handle defer(F&& f) {
      |                               ^
/usr/include/oneapi/tbb/task_group.h:588:5: error: two or more data types in declaration of ‘scopeExit_588’
  588 |     d2::task_handle defer(F&& f) {
      |     ^~

```
Builds carried out with sources before this commit are fine

This is the compiler version:
```
 gcc --version
gcc (GCC) 14.2.1 20250207
Copyright (C) 2024 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Any hint as to what the problem might be would be appreciated. Thank you.

**Comment by wtbgagoa** [comment]
Solved by doing a clean build. Sorry for the noise.

**Comment by shadow11001** [comment]
I am still getting this error. 

`[ 82%] Building CXX object src/CMakeFiles/openspace-core.dir/util/threadpool.cpp.o
[ 83%] Building CXX object src/CMakeFiles/openspace-core.dir/util/timeconversion.cpp.o
[ 83%] Building CXX object src/CMakeFiles/openspace-core.dir/util/time.cpp.o
[ 83%] Building CXX object src/CMakeFiles/openspace-core.dir/util/timeline.cpp.o
[ 83%] Building CXX object src/CMakeFiles/openspace-core.dir/util/timemanager.cpp.o
[ 83%] Building CXX object src/CMakeFiles/openspace-core.dir/util/timerange.cpp.o
[ 83%] Building CXX object src/CMakeFiles/openspace-core.dir/util/touch.cpp.o
In file included from /home/morphon/.cache/aurman/openspace-git/src/OpenSpace/ext/ghoul/include/ghoul/lua/lua_helper.inl:30,
                 from /home/morphon/.cache/aurman/openspace-git/src/OpenSpace/ext/ghoul/include/ghoul/lua/lua_helper.h:620,
                 from /home/morphon/.cache/aurman/openspace-git/src/OpenSpace/build/src/CMakeFiles/openspace-core.dir/cmake_pch.hxx:9,
                 from <command-line>:
/usr/include/oneapi/tbb/task_group.h:588:21: error: non-local lambda expression cannot have a capture-default
  588 |     d2::task_handle defer(F&& f) {
      |                     ^~~~~
In file included from /usr/include/oneapi/tbb/partitioner.h:47,
                 from /usr/include/oneapi/tbb/parallel_for.h:27,
                 from /usr/include/tbb/parallel_for.h:17,
                 from /usr/include/c++/14.2.1/pstl/parallel_backend_tbb.h:25,
                 from /usr/include/c++/14.2.1/pstl/parallel_backend.h:20,
                 from /usr/include/c++/14.2.1/pstl/algorithm_impl.h:22,
                 from /usr/include/c++/14.2.1/pstl/glue_execution_defs.h:50,
                 from /usr/include/c++/14.2.1/execution:39,
                 from /home/morphon/.cache/aurman/openspace-git/src/OpenSpace/src/scene/scene_lua.inl:61,
                 from /home/morphon/.cache/aurman/openspace-git/src/OpenSpace/src/scene/scene.cpp:39:
/usr/include/oneapi/tbb/task_group.h: In lambda function:
/usr/include/oneapi/tbb/task_group.h:588:26: error: expected ‘{’ before ‘(’ token
  588 |     d2::task_handle defer(F&& f) {
      |                          ^
/usr/include/oneapi/tbb/task_group.h: At global scope:
/usr/include/oneapi/tbb/task_group.h:588:28: error: expected primary-expression before ‘&&’ token
  588 |     d2::task_handle defer(F&& f) {
      |                            ^~
/usr/include/oneapi/tbb/task_group.h:588:31: error: ‘f’ was not declared in this scope
  588 |     d2::task_handle defer(F&& f) {
      |                               ^
/usr/include/oneapi/tbb/task_group.h:588:5: error: two or more data types in declaration of ‘scopeExit_588’
  588 |     d2::task_handle defer(F&& f) {
      |     ^~
[ 83%] Building CXX object src/CMakeFiles/openspace-core.dir/util/transformationmanager.cpp.o
[ 83%] Building CXX object src/CMakeFiles/openspace-core.dir/util/universalhelpers.cpp.o
[ 83%] Building CXX object src/CMakeFiles/openspace-core.dir/util/versionchecker.cpp.o
cc1plus: note: unrecognized command-line option ‘-Wno-unknown-attributes’ may have been intended to silence earlier diagnostics
make[2]: *** [src/CMakeFiles/openspace-core.dir/build.make:1904: src/CMakeFiles/openspace-core.dir/scene/scene.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:3939: src/CMakeFiles/openspace-core.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
2025-04-26 18:14:56,765 - wrappers - makepkg - ERROR - makepkg query ['makepkg', '-cf', '--noconfirm'] failed in directory /home/morphon/.cache/aurman/openspace-git
`

I have done a fresh clean build and it still does it and I am using the same version of GCC as wtbgagoa.

**Comment by shadow11001** [comment]
Here is a fresh log of the build after clearing the cache:

```
[ 85%] Building CXX object src/CMakeFiles/openspace-core.dir/scene/scene.cpp.o
[ 85%] Building CXX object src/CMakeFiles/openspace-core.dir/scene/sceneinitializer.cpp.o
[ 85%] Building CXX object src/CMakeFiles/openspace-core.dir/scene/scenegraphnode.cpp.o
[ 85%] Building CXX object src/CMakeFiles/openspace-core.dir/scene/timeframe.cpp.o
[ 85%] Building CXX object src/CMakeFiles/openspace-core.dir/scene/translation.cpp.o
In file included from /home/morphon/.cache/aurman/openspace-git/src/OpenSpace/ext/ghoul/include/ghoul/lua/lua_helper.inl:30,
                 from /home/morphon/.cache/aurman/openspace-git/src/OpenSpace/ext/ghoul/include/ghoul/lua/lua_helper.h:620,
                 from /home/morphon/.cache/aurman/openspace-git/src/OpenSpace/build/src/CMakeFiles/openspace-core.dir/cmake_pch.hxx:9,
                 from <command-line>:
/usr/include/oneapi/tbb/task_group.h:588:21: error: non-local lambda expression cannot have a capture-default
  588 |     d2::task_handle defer(F&& f) {
      |                     ^~~~~
In file included from /usr/include/oneapi/tbb/partitioner.h:47,
                 from /usr/include/oneapi/tbb/parallel_for.h:27,
                 from /usr/include/tbb/parallel_for.h:17,
                 from /usr/include/c++/14.2.1/pstl/parallel_backend_tbb.h:25,
                 from /usr/include/c++/14.2.1/pstl/parallel_backend.h:20,
                 from /usr/include/c++/14.2.1/pstl/algorithm_impl.h:22,
                 from /usr/include/c++/14.2.1/pstl/glue_execution_defs.h:50,
                 from /usr/include/c++/14.2.1/execution:39,
                 from /home/morphon/.cache/aurman/openspace-git/src/OpenSpace/src/scene/scene_lua.inl:61,
                 from /home/morphon/.cache/aurman/openspace-git/src/OpenSpace/src/scene/scene.cpp:39:
/usr/include/oneapi/tbb/task_group.h: In lambda function:
/usr/include/oneapi/tbb/task_group.h:588:26: error: expected ‘{’ before ‘(’ token
  588 |     d2::task_handle defer(F&& f) {
      |                          ^
/usr/include/oneapi/tbb/task_group.h: At global scope:
/usr/include/oneapi/tbb/task_group.h:588:28: error: expected primary-expression before ‘&&’ token
  588 |     d2::task_handle defer(F&& f) {
      |                            ^~
/usr/include/oneapi/tbb/task_group.h:588:31: error: ‘f’ was not declared in this scope
  588 |     d2::task_handle defer(F&& f) {
      |                               ^
/usr/include/oneapi/tbb/task_group.h:588:5: error: two or more data types in declaration of ‘scopeExit_588’
  588 |     d2::task_handle defer(F&& f) {
      |     ^~
[ 85%] Building CXX object src/CMakeFiles/openspace-core.dir/scripting/lualibrary.cpp.o
[ 85%] Building CXX object src/CMakeFiles/openspace-core.dir/scripting/scriptengine.cpp.o
[ 85%] Building CXX object src/CMakeFiles/openspace-core.dir/scripting/scriptscheduler.cpp.o
[ 85%] Building CXX object src/CMakeFiles/openspace-core.dir/scripting/systemcapabilitiesbinding.cpp.o
[ 85%] Building CXX object src/CMakeFiles/openspace-core.dir/util/blockplaneintersectiongeometry.cpp.o
[ 85%] Building CXX object src/CMakeFiles/openspace-core.dir/util/boxgeometry.cpp.o
[ 85%] Building CXX object src/CMakeFiles/openspace-core.dir/util/collisionhelper.cpp.o
[ 85%] Building CXX object src/CMakeFiles/openspace-core.dir/util/coordinateconversion.cpp.o
[ 85%] Building CXX object src/CMakeFiles/openspace-core.dir/util/distanceconversion.cpp.o
cc1plus: note: unrecognized command-line option ‘-Wno-unknown-attributes’ may have been intended to silence earlier diagnostics
make[2]: *** [src/CMakeFiles/openspace-core.dir/build.make:1904: src/CMakeFiles/openspace-core.dir/scene/scene.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:3939: src/CMakeFiles/openspace-core.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
2025-04-26 18:36:05,540 - wrappers - makepkg - ERROR - makepkg query ['makepkg', '-cf', '--noconfirm'] failed in directory /home/morphon/.cache/aurman/openspace-git

```

I'm not sure what the problem seems to be with this.

**Comment by wtbgagoa** [comment]
Answered [here](https://github.com/OpenSpace/OpenSpace/issues/3624#issuecomment-2833414631).
